map_type: costmap

obstacle_range: 0.3 #Threshold of obstacles to be included in the costmap
raytrace_range: 0.3

transform_tolerance: 0.5

robot_radius: 0.5 #Inflating the robot virtually to allow better navigation 
inflation_radius: 2.0 #Inflates the obstacles to allow the robot to navigate in a space avoiding collisions

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
